from rich.console import Console

envs = dict(human_language="english", cache=None, root_path=None)
console = Console()
ext2language = {
    "py": "python",
    'cpp': "cpp",
    'c': "C",
    'json': "json",
    'md': "Markdown",
    'rs': "rust",
    "ts": "typescript",
    "js": "javascript",
    "tsx": "typescript",
    "jsx": "javascript",
}
scan_exts = []


def readme_header(args):
    return f"""
<div align="center">
    <a href="https://github.com/gusye1234/gpt-readme">
      <img src="https://img.shields.io/badge/written_by-GPT-green">
    </a>
    <a href="https://github.com/gusye1234/gpt-readme">
      <img src="https://img.shields.io/badge/could_be-Wrong-red">
    </a>
    <a href="https://pypi.org/project/gpt-readme/">
      <img src="https://img.shields.io/pypi/v/gpt-readme.svg">
    </a>
</div>

*This readme is generated by command: `gpt-readme --path="{args.path}" --demand="{args.demand}" --language="{args.language}"`*

"""
